### ISSUE TITLE
AssertionError: [] -- No transactions found

### ISSUE THREAD

**Issue by mapapuche** [pcko1/etherscan-python#11]
Hello,

When i try to get last transfer events of my account like that :

`eth_erc20_events = eth.get_erc20_token_transfer_events_by_address(address='0xa71ac2c62A1b477186f5CbF45d94fFcd5D7e5711', startblock=0, endblock=1000000, sort='des')`

I got  AssertionError: [] -- No transactions found

I'm not sure of what i should set on startblock & endblock, can you help please :) ?

My main goal is to find my pending and successfull transaction of last month.

**Comment by pcko1** [comment]
Hi, as you can see on [Etherscan](https://etherscan.io/address/0xa71ac2c62A1b477186f5CbF45d94fFcd5D7e5711) the latest transactions happened inside block `11775464` which is outside of the endblock limit you have set by an order of magnitude and this means you should extend your query limits. To find the latest block number, use `eth.get_block_number_by_timestamp`.
