### ISSUE TITLE
Add support for testnets

### ISSUE THREAD

**Issue by litneet64** [pcko1/etherscan-python#12]
Hi, I'm working on a [project](https://github.com/litneet64/etherscan-python) that relies on `etherscan-python` for communicating with Etherscan.io's API, and having support for querying stuff on the other testnets will come really handy for the end goal of it. 

Luckily, I already added that feature on a fork I did from this project following the overall "minimalism" (as said on the description) and also adding the testnets to the module tests with their own working/stable test cases (randomly sampled - [*]) along with a minimalist usage example on the README. 

[*] Unfortunately, I don't possess a PRO API key, so I couldn't find working test cases for the PRO endpoints nor I know if they are already passing with those parameters or not.

**Comment by litneet64** [comment]
Also, logs for testnets are not included as I think their existence on this repo is a decision for you to take, however their proper generation is already found on the module tests' code.

**Comment by pcko1** [comment]
@litneet64 apologies for the late reply, I somehow missed this notification. I have just accepted your PR! Unfortunately the `pro` methods are not supported for the test-nets by Etherscan.io but everything else seems to be working well. Thanks a lot for this contribution :)
