### ISSUE TITLE
USD values

### ISSUE THREAD

**Issue by testvinder** [pcko1/etherscan-python#17]
When downloading transaction data as CSV from etherscan it includes "TxnFee(USD)" and "Historical $Price/Eth". Is there any way to get these values from the APIs?

**Comment by pcko1** [comment]
Closing this as it's not an issue. I would highly recommend going through the documentation of the API as this package offers whatever the official [Etherscan.io API](https://etherscan.io/apis) offers in an 1:1 fashion.
