### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by wishes90** [pcko1/etherscan-python#2]
File "C:\defi\venv\lib\site-packages\etherscan\enums\fields_enum.py", line 1, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

Add depending, please.

**Comment by pcko1** [comment]
Hi, `dataclasses` is a builtin Python package that comes with Python `3.7+`. The recommended Python version for this repository is `3.8`. Kindly make sure your version conforms to this, otherwise create an environment from scratch as instructed in the `README.md` file.
