### ISSUE TITLE
Using package

### ISSUE THREAD

**Issue by julianlen** [pcko1/etherscan-python#3]
Hi there!

I'm trying to use etherscan-python in my project. For that, I installed it through `pip` by using `pip install etherscan-python`. 

Then when I try to import it

from etherscan import Etherscan
eth = Etherscan('mykey')

It throws:

FileNotFoundError: Package has no location <module 'etherscan.configs' (namespace)>

Any suggestion?

Thank you in advance!

**Comment by pcko1** [comment]
Hi, issue verified and I am working on a fix. Please `git clone` and install from source by running `pip install .` as a quick fix (and not via PyPI). Thanks!

**Comment by pcko1** [comment]
@julianlen the issue should now be solved, kindly let me know if everything works ok after `pip install`ing the new `v2.0.2`.
