### ISSUE TITLE
ImportError: cannot import name 'Etherscan'

### ISSUE THREAD

**Issue by rajeshkalakoti** [pcko1/etherscan-python#6]
I encountered this error when I tried to use the package.

**Comment by pcko1** [comment]
Hi, could you please provide a code snippet that replicates the exact problem?

**Comment by rajeshkalakoti** [comment]
Hello, It's solved. Thanks for your reply. I appreciate you.

**Comment by rajeshkalakoti** [comment]
ImportError Traceback (most recent call last)
in ()
----> 1 from etherscan import Etherscan

ImportError: cannot import name 'Etherscan

**Comment by pcko1** [comment]
Kindly make sure that the package is installed and up-to-date by running `pip install etherscan-python==2.0.2`
