### ISSUE TITLE
how can I export the hack list from label word cloud of etherscan.io

### ISSUE THREAD

**Issue by LynnZhang9** [pcko1/etherscan-python#9]
Thank you for your work. I would like to know whether I can apply your package to obtain the list of hack address from etherscan?

**Comment by pcko1** [comment]
Hi! that would be a very cool feature indeed, but it is currently not offered by the official Etherscan API endpoints, unfortunately. In this package, I just mirror those endpoints using a `python` implementation which means that I cannot extend them from my end.
